### ISSUE TITLE
docx4j-6.0.0 - UTF-8 XML Encoding error for all our documents!

### ISSUE THREAD

**Issue by axelock** [plutext/docx4j#313]
HI!

We try to move on for the next version, but we have encountered a very serious problem, that makes the docx4j unusable!

We are from Hungary, having some characters not included in Latin-1: "őŐűŰ" (These are in Latin-2)
This was not a problem, because Word (and docx4j) using UTF-8 as the encoding of internal XMLs like document.xml

Until 6.0.0 - what misteriously modifies the XML header fom the normal

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
`
to this:
`<?xml version="1.0" ?>`

AND the actual encoding of the XML text is not UTF-8, what the XML specification requires when the "encoding" attribute omitted from the header!
(It will be something like the our platfrom-default Latin-2.)

The Microsoft Word (and any XML parsers) throws an "XML Formatting error" message when we try to open the document! 

This is a really simple test program (But you may have to set the system encoding to ISO8859-2 for the effect.)
---8<-------------------------
```
import java.io.File;
import org.docx4j.Docx4J;
import org.docx4j.openpackaging.packages.WordprocessingMLPackage;
public class Docx4jUTF8Test {
  public static void main(String[] args) {
    try {
      WordprocessingMLPackage wordPackage = WordprocessingMLPackage.createPackage();
      wordPackage.getMainDocumentPart().addParagraphOfText("őŐűŰ Árvíztűrő Tükörfúrógép"); // Some characters not in Latin-1 :)
      Docx4J.save(wordPackage, new File("C:/TestResult1.docx"));
      System.out.println("Done.");
    } catch (Exception e) {
      e.printStackTrace();
    }
  }
}
```
--->8-------------------------

Minimal set of jars for run this:
docx4j-6.0.0.jar
guava-20.0.jar
xalan-2.7.2.jar
commons-io-2.5.jar
commons-compress-1.12.jar
slf4j-api-1.7.25.jar
slf4j-log4j12-1.7.25.jar
log4j-1.2.13.jar

Please help us! :)

Kind Regards,

Gabor

**Comment by plutext** [comment]
Thanks for this; fixed by https://github.com/plutext/docx4j/commit/78e6babe0e964c8f83051a4c7fd68db45ef6e9ba

Fix is in https://docx4java.org/docx4j/docx4j-ImportXHTML-nightly-20180801.jar

Please verify fix; I will make a formal 6.0.1 in a couple of days

**Comment by axelock** [comment]
Hi Jason!

Not really in docx4j-ImportXHTML-nightly-20180801.jar but in this:
https://docx4java.org/docx4j/docx4j-nightly-20180802.jar

Thank you very much for the quick answer!!

It is working for the document.xml and header1.xml!
( The  encoding="UTF-8"  still not visible in the header, but this is OK.)


*** But the styles.xml (for example) still has bad encoding! ***

(We have styles with accented names.)

Kind Regards,

Gabor

**Comment by plutext** [comment]
Ooops, yes that's right.  Wrong link...

I see the encoding set in a new header in a new document.  (If you are opening an existing docx in docx4j and docx4j does not need to unmarshal a header part, it won't, and what you see when you save it will be identical to what was there before)  Same goes for styles.xml....

**Comment by axelock** [comment]
Ooooops... My bad!!

*** Everything is OK! :D ***

(I forgot that I've created a new Eclipse project for the Docx4jUTF8Test and I changed the jar reference only there, but not in my original tested project...  :/  )

Thank you for the quick response again!
I'm sorry for the misleading...

Kind regards,
Gabor

**Comment by plutext** [comment]
Hi Gabor,

Just following up on this, you'll see we've now released 6.0.1 with the fix.

But I'm curious as to what software combo actually had problems with your test program?

For example, the output docx works for me on Win 10 with Word 2016, where Powershell returns iso-8859-1 / Windows-1252 for the command:  [System.Text.Encoding]::Default

And you'd expect it to, since it should default to UTF-8, see:
- https://www.docx4java.org/forums/docx-java-f6/character-encoding-of-word-docs-t470.html
- http://www.opentag.com/xfaq_enc.htm#enc_default
- https://stackoverflow.com/questions/16361909/how-default-is-the-default-encoding-utf-8-in-the-xml-declaration

(If you wrote that test program in Eclipse, you need to ensure its encoding (right click, properties) is UTF-8, otherwise it may be a case of "garbage in..." )

cheers .. Jason

**Comment by axelock** [comment]
Hi Jason!

These ary my Windows 10 setttings:

PS> [System.Text.Encoding]::Default
IsSingleByte      : True
BodyName          : iso-8859-2
EncodingName      : közép-európai (Windows)
HeaderName        : windows-1250
WebName           : windows-1250
WindowsCodePage   : 1250
IsBrowserDisplay  : True
IsBrowserSave     : True
IsMailNewsDisplay : True
IsMailNewsSave    : True
EncoderFallback   : System.Text.InternalEncoderBestFitFallback
DecoderFallback   : System.Text.InternalDecoderBestFitFallback
IsReadOnly        : True
CodePage          : 1250

We have the latest, updating Office 365 / Word 2016 32 bit, Hungarian
edition


We have accustomed to this (day-to-day) problem, NEVER using text-byte
conversion without explicit encoding information.

We can advice this to anyone who making software with a tiny chance for
using it internatonally...  ;)


Kind Regards,

Gabor

Jason Harrop <notifications@github.com> ezt írta (időpont: 2018. aug. 3.,
P, 23:55):
